### ISSUE TITLE
What's the purpose of beginning `count` at 10000000?

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [PaulStoffregen/USB-Serial-Print-Speed-Test#2]
In `setup()`:
```
count = 10000000;
```
I'm unable to run and test this right now, but why begin count at 10000000 instead of 0? I assume this was a typo as I don't see the purpose in this.

**Comment by PaulStoffregen** [comment]
The number of characters printed per line remains consistent, until you've printed 90000000 lines.

**Comment by ElectricRCAircraftGuy** [comment]
I see; that makes perfect sense. A 1-line comment there would be helpful to explain the "why".

**Comment by ElectricRCAircraftGuy** [comment]
I guess a good alternative would be to print the number as binary or hex with leading zeros, but that's most easily done with `printf()` :), and I've seen on the Arduino developers email the past couple days where that discussion leads. :)
